model: gpt-4.1
# model: gpt-5
weak-model: gpt-4.1-mini
editor-model: gpt-4.1-mini

read:
  - CONVENTIONS.md
  - client/shared/CONVENTIONS.md
  - client/ios/CONVENTIONS.md
  - server/CONVENTIONS.md
  - prompt.md

subtree-only: true
auto-commits: false
