name: Update project graph
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Generate Mermaid graph
        working-directory: server
        run: sbt -v projectDepsMermaid

      # Optional: insert the Mermaid block into README between markers
      - name: Update README section
        shell: bash
        run: |
          START="<!-- modules-graph:start -->"
          END="<!-- modules-graph:end -->"
          BLOCK="$(cat docs/modules.mmd.md)"
          awk -v start="$START" -v end="$END" -v repl="$BLOCK" '
            BEGIN { inblock=0 }
            {
              if ($0 ~ start) { print; print repl; inblock=1; next }
              if ($0 ~ end)   { print; inblock=0; next }
              if (!inblock)   print
            }' README.md > README.md.new
          mv README.md.new README.md

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update project graph"
          file_pattern: docs/modules.mmd.md README.md
